import "./globals.css";

import { JUANA } from "./styles/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${JUANA.variable} font-serif`}>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/vrt4lcx.css" />
      </head>
      <body>{children}</body>
    </html>
  );
}
